"""Replace unique constraint with index for document uniqueness

Revision ID: 13c426e84b5f
Revises: 156932104802
Create Date: 2025-11-12 19:50:02.110517
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '13c426e84b5f'
down_revision = '156932104802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_documents_name_note_equipment'), 'documents', type_='unique')
    op.create_index('ix_documents_unique_name_note_equipment', 'documents', ['doc_name', 'equipment_id', sa.literal_column("coalesce(note, '')")], unique=True)
    op.create_index(op.f('ix_equipment_factory_no'), 'equipment', ['factory_no'], unique=True)
    op.create_unique_constraint('uq_equipment_factory_no', 'equipment', ['factory_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_equipment_factory_no', 'equipment', type_='unique')
    op.drop_index(op.f('ix_equipment_factory_no'), table_name='equipment')
    op.drop_index('ix_documents_unique_name_note_equipment', table_name='documents')
    op.create_unique_constraint(op.f('uq_documents_name_note_equipment'), 'documents', ['doc_name', 'note', 'equipment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
